FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y mpich build-essential && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY sr.c .

RUN mpicc sr.c -o sr

RUN useradd -m mpiuser
USER mpiuser

CMD ["mpirun", "-n", "2", "./sr"]
