#!/usr/bin/env python3
"""
Feature coverage analysis for CWL conformance test results.

This script aggregates JUnit results generated by CWL runners
(cwltool, Toil, StreamFlow) across multiple HPC systems and computes
feature-level coverage based on CWL conformance test definitions.

The output is a LaTeX document containing per-runner, per-version
coverage tables across HPC environments matching the requested styling theme.
"""
import argparse
import logging
import xml.etree.ElementTree
from collections import defaultdict
from pathlib import Path
from typing import Any

import requests
from ruamel.yaml import YAML

yaml = YAML(typ="safe")
"""Parser."""

OUTPUT_DIR = Path("output")
SPEC_DIR = Path("specs")

RUNNERS = {
    "cwltool": "cwltool",
    "toil": "Toil",
    "streamflow": "StreamFlow",
}
"""Map of CWL Runners."""

# Full names mapping for display inside tables to match styles
HPC_NAMES = {
    "ft3": "FinisTerrae III",
    "lumi": "LUMI",
    "mn5": "MareNostrum 5"
}

HPCS = ["ft3", "lumi", "mn5"]
"""Clusters used."""

CWL_VERSIONS = {
    "v1.0": (
        "1.0.2",
        "https://raw.githubusercontent.com/common-workflow-language/common-workflow-language/v1.0.2/v1.0/conformance_test_v1.0.yaml",
    ),
    "v1.1": (
        "1.1.0",
        "https://raw.githubusercontent.com/common-workflow-language/cwl-v1.1/v1.1.0/conformance_tests.yaml",
    ),
    "v1.2": (
        "1.2.1",
        "https://raw.githubusercontent.com/common-workflow-language/cwl-v1.2/v1.2.1/conformance_tests.yaml",
    ),
}
"""Map of CWL version, with its final version form, and the YAML file."""


def setup_logger() -> None:
    """Configure logging for the report generation process."""
    logging.basicConfig(
        filename="report_feature_coverage.log",
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="CWL feature coverage report generator"
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output"),
        help="Base directory containing runner results",
    )

    parser.add_argument(
        "--runner",
        action="append",
        choices=list(RUNNERS.keys()),
        help="Limit to specific runner(s) (repeatable)",
    )

    parser.add_argument(
        "--spec",
        action="append",
        choices=list(CWL_VERSIONS.keys()),
        help="Limit to specific CWL spec(s) (repeatable)",
    )

    return parser.parse_args()


def ensure_yaml(version_key: str, url: str) -> Path:
    """Ensure a CWL conformance YAML file exists locally."""
    SPEC_DIR.mkdir(exist_ok=True)
    path = SPEC_DIR / f"{version_key}.yaml"

    if path.exists():
        logging.info("Using cached YAML: %s", path)
        return path

    logging.info("Downloading YAML for version %s", version_key)

    response = requests.get(url)
    response.raise_for_status()

    path.write_text(response.text)
    return path


def parse_yaml(yaml_path: Path) -> dict[str, dict[str, Any]]:
    """Parse CWL conformance YAML and index tests by ID."""
    with open(yaml_path, "r") as f:
        data = yaml.load(f)

    index: dict[str, dict[str, Any]] = {}

    for test in data:
        if not isinstance(test, dict):
            logging.warning("Invalid test definition: %s", test)
            continue

        test_id = test.get("id")
        if test_id is None:
            continue

        test_id = str(test_id)
        test_id = normalize_test_id(test_id)
        if not test_id:
            logging.warning("Invalid test ID: %s", test_id)
            continue

        index[test_id] = {
            "features": test.get("tags", []),
            "doc": test.get("doc", ""),
        }

    return index


def parse_junit(xml_path: Path) -> dict[str, str]:
    """Parse JUnit XML results into a mapping of test ID → status."""
    tree = xml.etree.ElementTree.parse(xml_path)
    root = tree.getroot()

    results: dict[str, str] = {}

    for tc in root.iter("testcase"):
        url = tc.attrib.get("url")
        if url and "#" in url:
            test_id = url.split("#")[-1]
        else:
            test_id = tc.attrib.get("name") or tc.attrib.get("file") or tc.attrib.get("classname")

        if not test_id:
            logging.warning("Invalid test ID: %s", tc.attrib)
            continue

        test_id = normalize_test_id(test_id)

        if tc.find("failure") is not None or tc.find("error") is not None:
            status = "failed"
        elif tc.find("skipped") is not None:
            status = "skipped"
        else:
            status = "passed"

        results[test_id] = status

    return results


def collect_all(
        output_dir: Path,
        runners_filter: set[str] | None = None,
        versions_filter: set[str] | None = None,
) -> list[tuple[str, str, str, str, Path]]:
    """Collect all JUnit test runs from the output directory."""
    runs = []

    for runner in RUNNERS:
        if runners_filter and runner not in runners_filter:
            continue

        runner_dir = output_dir / runner

        if not runner_dir.exists():
            logging.warning("Missing runner directory: %s", runner_dir)
            continue

        for hpc in runner_dir.iterdir():
            for version in hpc.iterdir():

                if versions_filter and version.name not in versions_filter:
                    continue

                for mode in version.iterdir():
                    junit = mode / "junit.xml"

                    if junit.exists():
                        runs.append((runner, hpc.name, version.name, mode.name, junit))
                    else:
                        logging.warning("Missing JUnit file: %s", junit)

    return runs


def compute_feature_coverage(runs, yaml_index):
    """Compute feature-level coverage across runners, versions, and HPC systems."""
    stats = defaultdict(lambda: {"passed": 0, "total": 0})

    for runner, hpc, version, mode, junit in runs:
        results = parse_junit(junit)

        for test_id, status in results.items():
            if not test_id:
                continue

            meta = yaml_index.get(test_id)
            if not meta:
                logging.warning("Missing metadata for test %s", test_id)
                continue

            features = meta.get("features") or []
            if not isinstance(features, list):
                logging.warning("Invalid features for test %s: %s", test_id, features)
                continue

            for feature in features:
                key = (runner, version, feature, hpc)

                stats[key]["total"] += 1
                if status == "passed":
                    stats[key]["passed"] += 1

    return stats


def latex_escape(text: str) -> str:
    """Escape LaTeX special characters."""
    return (
        text.replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("$", r"\$")
    )


def format_value(v: dict[str, int] | None) -> str:
    """Format coverage value for LaTeX output matching target table specs."""
    if not v or v["total"] == 0:
        return "—"

    value = 100 * v["passed"] / v["total"]
    formatted = f"{value:.1f} \%"

    if value == 100.0:
        formatted = r"\textbf{100.0} \%"

    return formatted


def print_latex(stats) -> None:
    """Render feature coverage tables in LaTeX format with the new style theme."""
    grouped = defaultdict(lambda: defaultdict(dict))

    for (runner, version, feature, hpc), v in stats.items():
        grouped[runner][version].setdefault(feature, {})
        grouped[runner][version][feature][hpc] = v

    print(r"\documentclass{article}")
    print(r"\usepackage{geometry}")
    print(r"\usepackage{array}")
    print(r"\usepackage{multirow}")
    print(r"\usepackage[table]{xcolor}")
    print(r"\usepackage{hhline}")
    print(r"\geometry{margin=1in}")
    print(r"\begin{document}")

    for runner in sorted(grouped.keys()):
        print(r"\clearpage")
        print(rf"\subsubsection*{{{RUNNERS[runner]} Feature Coverage}}")

        for version in sorted(grouped[runner].keys()):
            version_label = CWL_VERSIONS[version][0]
            features = grouped[runner][version]

            print(r"\begin{table}[ht!]")
            print(r"\centering")
            print(r"\setlength{\tabcolsep}{6pt}")
            print(r"\renewcommand{\arraystretch}{1.2}")

            # Layout definition matching style rules
            print(r"\begin{tabular}{|c|" + "c|" * len(HPCS) + "}")
            print(r"\hline")
            print(r"\rowcolor{lightgray!50}")

            header = (
                    r"\textbf{Feature} & "
                    + " & ".join([rf"\textbf{{{HPC_NAMES[h]}}}" for h in HPCS])
                    + r" \\"
            )
            print(header)
            print(r"\hline")

            for feature in sorted(features.keys()):
                hpc_map = features[feature]
                row = [latex_escape(feature)]

                for hpc in HPCS:
                    row.append(format_value(hpc_map.get(hpc)))

                print(" & ".join(row) + r" \\")

            print(r"\hline")
            print(r"\end{tabular}")
            print(rf"\caption{{Feature coverage for {RUNNERS[runner]} (v{version_label})}}")
            print(rf"\label{{tab:{runner}_feat_{version.replace('.', '')}}}")
            print(r"\end{table}")

    print(r"\end{document}")


def normalize_test_id(test_id: str) -> str:
    """Normalize CWL test IDs consistently across runners and specs."""
    test_id = str(test_id).strip()

    if "::" in test_id:
        test_id = test_id.split("::")[-1]

    test_id = test_id.replace(".cwltest.yaml", "")
    test_id = test_id.replace(".yaml", "")
    test_id = test_id.replace("/", ".")

    return test_id


def main() -> None:
    setup_logger()
    args = parse_args()

    logging.info("Starting feature coverage report")

    runners_filter = set(args.runner) if args.runner else None
    versions_filter = set(args.spec) if args.spec else None

    runs = collect_all(
        output_dir=args.output_dir,
        runners_filter=runners_filter,
        versions_filter=versions_filter,
    )

    yaml_index = {}
    for version_key, (_, url) in CWL_VERSIONS.items():
        yaml_index.update(parse_yaml(ensure_yaml(version_key, url)))

    stats = compute_feature_coverage(runs, yaml_index)
    print_latex(stats)

    logging.info("Completed feature coverage report")


if __name__ == "__main__":
    main()
