# File generated by cwl2click v0.6.0
# timestamp: 2026-02-14T01:23:11.043

__all__ = []

from click.compile_sr.cwl_impl import execute as compile_sr.cwl_command
from click.run_sr_mpirun.cwl_impl import execute as run_sr_mpirun.cwl_command

from pathlib import Path

import click







# None
__all__.append("mpicc")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# None = "click.compile_sr.cwl:mpicc"

mpicc = click.Command(
    name="mpicc",
    callback=compile_sr.cwl_command,
    help="No info provided",
    short_help="Compile sr.c with mpicc",
    params=[
            click.Option(
            ["--compile-sr.cwl#source"],
            "compile_sr.cwl#source",
            type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
            multiple=False,
            required=True,
            is_flag=False,
        ),
            click.Option(
            ["-o"],
            "compile_sr.cwl#output_name",
            type=click.STRING,
            multiple=False,
            required=True,
            is_flag=False,
        ),
    ]
)






# None
__all__.append("mpirun")
# NOTE
# Do not forget to add the section below in your `pyproject.toml` file
#  
# [project.scripts]
# None = "click.run_sr_mpirun.cwl:mpirun"

mpirun = click.Command(
    name="mpirun",
    callback=run_sr_mpirun.cwl_command,
    help="No info provided",
    short_help="Run compiled sr using mpirun",
    params=[
            click.Option(
            ["-np"],
            "run_sr_mpirun.cwl#np",
            type=click.INT,
            multiple=False,
            required=True,
            is_flag=False,
        ),
            click.Option(
            ["--run-sr-mpirun.cwl#executable"],
            "run_sr_mpirun.cwl#executable",
            type=click.Path(path_type=Path, exists=True, readable=True, resolve_path=True, file_okay=True, dir_okay=False),
            multiple=False,
            required=True,
            is_flag=False,
        ),
            click.Option(
            ["--run-sr-mpirun.cwl#msg_size"],
            "run_sr_mpirun.cwl#msg_size",
            type=click.INT,
            multiple=False,
            required=True,
            is_flag=False,
        ),
            click.Option(
            ["--run-sr-mpirun.cwl#niter"],
            "run_sr_mpirun.cwl#niter",
            type=click.INT,
            multiple=False,
            required=True,
            is_flag=False,
        ),
    ]
)


